# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    translator:
        enabled: true
        fallback: "%env(LOCALE)%"
        default_path: '%kernel.project_dir%/translations'
    secret: '%env(APP_SECRET)%'
    router:
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation:
        enable_annotations: true
    templating:
        engines: ['twig']
    default_locale: "%env(LOCALE)%"
    trusted_hosts: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: session.handler.native_file
        save_path: "%kernel.project_dir%/var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
